name: First Workflow
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:  
  first-job:
    runs-on: ubuntu-latest

    steps:
    - name: Printing Greetings text
      run: echo "Hello World!"
    - name: Printing Goodbay
      run: echo "Your first job is done, Goodbay!"
      
